In [1]:
# for package auto reload
%load_ext autoreload
%autoreload 2

# for better rendering of plots in jupyter notebook
%matplotlib inline

In [ ]:
# base modules
from pathlib import Path

# base modules
from collections import defaultdict

# for manipulating data
import numpy as np
import pandas as pd

In [ ]:
from pytrends.request import TrendReq
import time
import random

In [4]:
path_to_repo = Path('..').resolve()
path_to_data = path_to_repo / 'data'

In [5]:
df_raw = pd.read_csv(path_to_data / 'vestiaire.csv', low_memory = False)

In [6]:
df_raw = df_raw.convert_dtypes()

In [7]:
df_raw

,product_id,product_type,product_name,product_description,product_keywords,product_gender_target,product_category,product_season,product_condition,product_like_count,...,warehouse_name,seller_id,seller_username,usually_ships_within,seller_country,seller_products_sold,seller_num_products_listed,seller_community_rank,seller_num_followers,seller_pass_rate
0,43247626,Wool mini skirt,Wool mini skirt Miu Miu Grey size S Internatio...,Miu Miu – Pleated mini skirt Size: 36 (S) Wai...,Miu Miu Wool Skirts,Women,Women Clothing,Autumn / Winter,Never worn,34,...,Tourcoing,25775970,vitalii25775970,<NA>,Germany,3,14,0,13,0.0
1,43247441,Jacket,Jacket Barbara Bui Navy size 42 FR in Cotton,For selling nice women's suit Barbara Bui size...,Barbara Bui Cotton Jackets,Women,Women Clothing,All seasons,Very good condition,1,...,Tourcoing,13698770,olivia13698770,<NA>,Belgium,0,0,0,8,0.0
2,43246517,Wool coat,Wool coat Comme Des Garcons White size S Inter...,Magnificent boiled wool coat. I bought it in t...,Comme Des Garcons Wool Coats,Women,Women Clothing,Autumn / Winter,Very good condition,2,...,Tourcoing,6042365,cecilia6042365,1-2 days,Spain,58,69,0,62,96.0
3,43246507,Mini skirt,Mini skirt MSGM Black size 38 IT in Polyester,MSGM Skirt Black Printed Raw-Edge & Embroidere...,MSGM Polyester Skirts,Women,Women Clothing,All seasons,Very good condition,0,...,Brooklyn,13172949,gretchen13172949,1-2 days,United States,63,274,126346,131,96.0
4,43246417,Vegan leather trousers,Vegan leather trousers LVIR Black size 36 FR i...,LVIR black grained faux leather trousers size ...,LVIR Vegan leather Trousers,Women,Women Clothing,All seasons,Very good condition,1,...,Crawley,2578605,crunchykat,3-5 days,United Kingdom,19,14,102821,40,89.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900509,41538360,Glitter trainers,Glitter trainers Bally Gold size 38 EU in Glit...,"Bally Vita Parcours sneakers. PPleather, suede...",Bally Glitter Trainers,Women,Women Shoes,All seasons,Good condition,1,...,Tourcoing,8849230,lauragua,1-2 days,Italy,40,17,391778,104,100.0
900510,41532271,Leather heels,Leather heels Casadei Black size 38.5 EU in Le...,Trendy and classic Casadei high-heel pumps Mad...,Casadei Leather Heels,Women,Women Shoes,All seasons,Good condition,1,...,Tourcoing,5448248,bettina5448248,1-2 days,Austria,26,99,51408,75,89.0
900511,41538140,Leather cowboy boots,Leather cowboy boots Ash Black size 36 EU in L...,Very good quality leather boots Worn once Elas...,Ash Leather Boots,Women,Women Shoes,All seasons,Very good condition,0,...,Tourcoing,9347694,sylvie9347694,<NA>,France,0,2,0,3,0.0
900512,41537603,Leather ballet flats,Leather ballet flats Lauren Ralph Lauren Black...,Very beautiful ballet flats like new. I don't ...,Lauren Ralph Lauren Leather Ballet flats,Women,Women Shoes,All seasons,Very good condition,27,...,Tourcoing,24074881,marina24074881,1-2 days,Italy,2,7,0,11,100.0
900513,41534820,J'adior cloth sandal,J'adior cloth sandal Dior Beige size 38 EU in ...,"Dior J’adior slingback sandals pumps New, nev...",Dior J'adior Sandals,Women,Women Shoes,Spring / Summer,Never worn,47,...,Tourcoing,24557483,shop24557483,1-2 days,Romania,66,354,0,195,75.0

Sort brand names by order of counts.

In [9]:
brand_counts = df_raw['brand_name'].value_counts().reset_index()

brand_counts

             brand_name  count
0                 Gucci  41009
1              Burberry  24018
2       Dolce & Gabbana  22024
3                 Prada  20972
4                Hermès  18711
...                 ...    ...
8879  Carla Montanarini      1
8880         Pako Litto      1
8881           Themoirè      1
8882         Le Capsole      1
8883               Aera      1

[8884 rows x 2 columns]

Extract and brand names as a list.

In [10]:
brands_sorted = brand_counts["brand_name"].tolist()

brands_sorted

['Gucci',
 'Burberry',
 'Dolce & Gabbana',
 'Prada',
 'Hermès',
 'Louis Vuitton',
 'Chanel',
 'Nike',
 'Valentino Garavani',
 'Balenciaga',
 'Dior',
 'Fendi',
 'Adidas',
 'Saint Laurent',
 'Versace',
 'Polo Ralph Lauren',
 'Christian Louboutin',
 'Bottega Veneta',
 'Yves Saint Laurent',
 'Dsquared2',
 'Givenchy',
 'Salvatore Ferragamo',
 "Tod's",
 'Max Mara',
 'Celine',
 'Alexander McQueen',
 'Jimmy Choo',
 'Dior Homme',
 'Moncler',
 'Miu Miu',
 'Moschino',
 'Michael Kors',
 'D&G',
 'Sandro',
 'Boss',
 'Emporio Armani',
 'Tommy Hilfiger',
 'Acne Studios',
 'Kenzo',
 'Missoni',
 'Lanvin',
 'Giorgio Armani',
 'JORDAN',
 'Off-White',
 "Levi's",
 'Comme Des Garcons',
 'Diesel',
 'Tom Ford',
 'Loro Piana',
 'Balmain',
 'Lacoste',
 'GUESS',
 'Brunello Cucinelli',
 'Ray-Ban',
 'Roberto Cavalli',
 'Chloé',
 'Etro',
 'Ermenegildo Zegna',
 'Hogan',
 'Maje',
 'Cartier',
 "Church's",
 'Stone Island',
 'Maison Martin Margiela',
 'Ralph Lauren',
 'Giuseppe Zanotti',
 'Gianni Versace',
 'Paul Smith',
 'Isabel Marant',
 'Calvin Klein',
 'Hugo Boss',
 'Coach',
 'New Balance',
 'Zadig & Voltaire',
 'Philipp Plein',
 'The Kooples',
 'Omega',
 'Golden Goose',
 'Just Cavalli',
 'Marni',
 'Loewe',
 'Versace Jeans Couture',
 'Converse',
 'Massimo Dutti',
 'Jean Paul Gaultier',
 'Bally',
 'Supreme',
 'Yeezy x Adidas',
 'Timberland',
 'Jil Sander',
 'Ganni',
 'Vivienne Westwood',
 'The North Face',
 'Pinko',
 'Tory Burch',
 'Stella McCartney',
 'Ugg',
 'Bvlgari',
 'Barbour',
 'Dr. Martens',
 'Puma',
 'Rolex',
 'Liu.Jo',
 'Armani Jeans',
 'Palm Angels',
 'Stuart Weitzman',
 'SEIKO',
 'Elisabetta Franchi',
 'Carrera',
 'Carhartt',
 'Marc Jacobs',
 'Vans',
 'Woolrich',
 'Gianvito Rossi',
 'Isabel Marant Etoile',
 'Napapijri',
 'Emilio Pucci',
 'Sergio Rossi',
 'Jacquemus',
 'Cos',
 'Rick Owens',
 'Dries Van Noten',
 'CALVIN KLEIN JEANS',
 'Diane Von Furstenberg',
 'Lauren Ralph Lauren',
 'Santoni',
 'Gianfranco Ferré',
 'Karl Lagerfeld',
 'Max Mara Weekend',
 'Ted Baker',
 'MARINA RINALDI',
 'Trussardi',
 'Escada',
 'Marc by Marc Jacobs',
 'All Saints',
 'Ba&sh',
 'Zimmermann',
 'Manolo Blahnik',
 'Ami',
 'Gucci X Adidas',
 'Patrizia Pepe',
 'Sézane',
 'Carolina Herrera',
 'Fay',
 'Pierre Cardin',
 'John Richmond',
 'Casadei',
 'Blumarine',
 'Stussy',
 'Max & Co',
 'Armani Collezioni',
 'Twinset',
 'Dkny',
 'Kate Spade',
 'Helmut Lang',
 'Persol',
 'Moschino Love',
 'Brioni',
 'Issey Miyake',
 'Aquazzura',
 'Tag Heuer',
 'Belstaff',
 'Claudie Pierlot',
 'MCM',
 'La Perla',
 'Blauer',
 'Canada Goose',
 'Yohji Yamamoto',
 'See by Chloé',
 'Intrend',
 'Pierre Balmain',
 'Armani Exchange',
 'Alexander Wang',
 'Cesare Paciotti',
 '& Other Stories',
 'APC',
 'Reebok',
 'Iro',
 'Iceberg',
 'Alaïa',
 'Malo',
 'Red Valentino Garavani',
 'Cp Company',
 'Versus',
 'Self-Portrait',
 'Gant',
 'MM6',
 'Dondup',
 'JM Weston',
 'M Missoni',
 'American Vintage',
 'Versace Collection',
 'Roger Vivier',
 'Fratelli Rossetti',
 'Steve Madden',
 'Reformation',
 'Ermanno Scervino',
 'Amiri',
 'Totême',
 'Moschino Cheap And Chic',
 'JACOB COHEN',
 'Mcq',
 'Tiffany & Co',
 'Saucony',
 'Bikkembergs',
 'PAUL&SHARK',
 'Rag & Bone',
 'Schott',
 'Furla',
 'Thom Browne',
 'Birkenstock',
 'Canali',
 'Sportmax',
 'Clarks',
 'Patagonia',
 'Free People',
 'Plein Sport',
 'DUNHILL',
 'Fila',
 'Breitling',
 'GCDS',
 'J.Crew',
 'A Bathing Ape',
 'Chopard',
 'Bcbg Max Azria',
 'Tommy Jeans',
 'Fred Perry',
 'Champion',
 'Berluti',
 'Raf Simons',
 'Nina Ricci',
 'Asics',
 'Montblanc',
 'The Row',
 'Citizen',
 'Longines',
 'MARITHÉ & FRANÇOIS GIRBAUD',
 'Class Cavalli',
 'MSGM',
 'Corneliani',
 'Aspesi',
 'Joseph',
 'GEOX',
 'LUISA SPAGNOLI',
 'Neil Barrett',
 'John Galliano',
 'Borsalino',
 'Tissot',
 'Colmar',
 'Theory',
 'Reiss',
 'Sonia Rykiel',
 'Aquascutum',
 'Vetements',
 'Marella',
 'Brooks Brothers',
 'OAKLEY',
 'Kiton',
 'Peuterey',
 'Undercover',
 'Baldinini',
 'Ann Demeulemeester',
 'Courrèges',
 'Y-3',
 'Ash',
 'Lancel',
 'Attico',
 'IWC',
 'ALVIERO MARTINI',
 'Casio',
 'Longchamp',
 'Alice & Olivia',
 'Pal Zileri',
 'AMINA MUADDI',
 'Cerruti',
 'Christian Lacroix',
 'Free Lance',
 'Bogner',
 'Axel Arigato',
 'Zegna',
 'Lululemon',
 'Scotch & Soda',
 'JW Anderson',
 'Khaite',
 'Veja',
 'Paraboot',
 'Boggi',
 'Junya Watanabe',
 'Common Projects',
 'Juicy Couture',
 'Herno',
 'Oliver Peoples',
 'POLICE',
 'Gas',
 'The North Face x Gucci',
 'Victoria Beckham',
 'Camper',
 'Pollini',
 'Anthropologie',
 'Replay',
 'Swatch',
 'Fossil',
 'Vince',
 'Anine Bing',
 'Gerard Darel',
 'Oscar De La Renta',
 'Costume National',
 'Marc Cain',
 'E.Marinella',
 'Filippa K',
 'Rene Caovilla',
 'Play Comme des Garçons',
 'Marcelo Burlon',
 'Hackett London',
 'Cole Haan',
 'G STAR RAW',
 'Trussardi Jeans',
 'Tara Jarmon',
 'by Malene Birger',
 'Philippe Model',
 'Paco Rabanne',
 'Proenza Schouler',
 'Nanushka',
 'HARLEY DAVIDSON',
 'Ulla Johnson',
 'K-Way',
 'Emanuel Ungaro',
 'Comptoir Des Cotonniers',
 'Banana Republic',
 'Swarovski',
 'Parajumpers',
 'ZENOBI',
 'Z Zegna',
 "Max Mara 'S",
 'Rick Owens Drkshdw',
 'Vogue',
 'DICKIES',
 'Frame',
 'Le Silla',
 'Lk Bennett',
 'John Lobb',
 'Y-3 by Yohji Yamamoto',
 'SUPERDRY',
 'Heron Preston',
 'GIANMARCO VENTURI',
 'ESPRIT',
 'Our Legacy',
 'Romeo Gigli',
 'Veronica Beard',
 'Alberta Ferretti',
 'Zilli',
 'True Religion',
 'Christian Dior',
 'Carhartt WIP',
 'Vivienne Westwood Anglomania',
 'Ikks',
 'Thierry Mugler',
 'Trickers London',
 '7 For All Mankind',
 'Mac Duggal',
 'Arket',
 '3.1 Phillip Lim',
 'Leonard',
 'LES COPAINS',
 'Tudor',
 'Ralph Lauren Purple Label',
 'Christopher Esber',
 'Yeezy',
 '1017 ALYX 9SM',
 'NEW ERA',
 'PARIS TEXAS',
 'Hysteric Glamour',
 'COLUMBIA',
 'Salomon',
 'Mulberry',
 'Porsche Design',
 'Max Mara Studio',
 'Diadora',
 'Invicta',
 'Mugler',
 'Suitsupply',
 'Stefano Ricci',
 'Daniele Alessandrini',
 'SISLEY',
 'N°21',
 'Nike x Off-White',
 'Ballantyne',
 'PEPE JEANS',
 'Kappa',
 'Sergio Tacchini',
 'Guy Laroche',
 'Carven',
 'Hamilton',
 'Frye',
 'By Far',
 'Palace',
 'Panerai',
 'MISS SIXTY',
 'Nike Acg',
 'Zenith',
 'Harmont & Blaine',
 'Lemaire',
 'Repetto',
 'Movado',
 'Closed',
 'Fred Mello',
 'Krizia',
 'Kenneth Cole',
 'Bulova',
 'Omega X Swatch',
 'Byblos',
 'Barbara Bui',
 'Faconnable',
 'LA MARTINA',
 'Cacharel',
 'Robert Clergerie',
 'FERRARI',
 'Pleats Please',
 'Galliano',
 'Eytys',
 'Jeffrey Campbell',
 'Chevignon',
 'Sacai',
 'Avirex',
 'Superga',
 'Maison Kitsune',
 'Evisu',
 'Agent Provocateur',
 'Vanessa Bruno',
 'Kurt Geiger',
 'Chrome Hearts',
 'Wolford',
 'Bimba y Lola',
 'North Sails',
 'Visvim',
 'Fabiana Filippi',
 'Samsoe & Samsoe',
 'ROCCOBAROCCO',
 'Madewell',
 'ED HARDY',
 'REFRIGIWEAR',
 'Linda Farrow',
 "ARC'TERYX",
 'Paul & Joe',
 'Pierre Hardy',
 'STEFANEL',
 'RINASCIMENTO',
 'Bugatti',
 'Charlotte Olympia',
 'Carlo Pignatelli',
 "VICTORIA'S SECRET",
 "Doucal's",
 'Under Armour',
 'Mach & Mach',
 'Herve Leger',
 'Agolde',
 'Jack & Jones',
 'St John',
 'Castaner',
 'NEEDLES',
 'Buscemi',
 'Agnès B.',
 'Casablanca',
 'Lee',
 'Sophia Webster',
 'Premiata',
 'CROCS',
 'Magda Butrym',
 'Dita',
 'Cazal',
 'Paule Ka',
 'Alpha Industries',
 'Altea',
 'Rouje',
 'GRAN SASSO',
 'Marine Serre',
 'JC De Castelbajac',
 'Adidas x Pharrell Williams',
 'Jeckerson',
 'Louis Feraud',
 'Mother',
 'Orciani',
 'Sorel',
 'BREIL',
 'Tagliatore',
 'Uterque',
 'Vagabond',
 'Farm Rio',
 'Boss Orange',
 'Geographical Norway',
 'ENRICO COVERI',
 'MINELLI',
 'ANTONY MORATO',
 'Maison Michel',
 'Moose Knuckles',
 'Marsèll',
 'eleventy',
 'CROCKETT & JONES',
 'Eres',
 'Bruno Magli',
 'CARLO COLUCCI',
 'JOOP!',
 'Essentiel Antwerp',
 'Sebago',
 'LAURA BIAGIOTTI',
 'Ann Taylor',
 'Apples of Gold',
 'Mauro Grifoni',
 'Crockett& Jones',
 'C.P. Company',
 'Represent',
 'Lardini',
 'S.T. Dupont',
 'J Brand',
 'John Varvatos',
 'MORESCHI',
 'Tiger Of Sweden',
 'Sam Edelman',
 'Atlantic Stars',
 'House of CB',
 'Rotate',
 'A-Cold-Wall',
 'Italia Independent',
 'Jeremy Scott Pour Adidas',
 'AMBUSH',
 'Magnanni',
 'Converse x Play Comme Des Garçons',
 'Cult Gaia',
 'Moncler Genius',
 "MARC O'POLO",
 'Gaelle Paris',
 'Mackage',
 'Misbhv',
 'Billionaire',
 'Lilly Pulitzer',
 'A.S.98',
 'Brooksfield',
 "Drake's",
 'Zapa',
 'Heschung',
 'Wrangler',
 'Adolfo Dominguez',
 'Whistles',
 'Vilebrequin',
 'Falconeri',
 'FABI',
 'CONBIPEL',
 'Sea New York',
 'NERO GIARDINI',
 'CAROLL',
 'JONAK',
 'Philosophy Di Lorenzo Serafini',
 'RADO',
 "Levi's Vintage Clothing",
 'Chiara Ferragni',
 'The Pangaia',
 'A. Testoni',
 'Philosophy Di Alberta Ferretti',
 'Umbro',
 'Borrelli',
 'Schutz',
 'Grenson',
 'Club Monaco',
 'Staud',
 "Y's",
 'Aigner',
 'Jaeger-Lecoultre',
 'Ralph Lauren Collection',
 'Alain Mikli',
 'Ellesse',
 'Isaia',
 'COP COPINE',
 'Y/Project',
 'Vicolo',
 'Forte_Forte',
 'Eileen Fisher',
 'Malone Souliers',
 'Selected',
 'Fear of God',
 'REDSKINS',
 'Helly Hansen',
 'R13',
 'French Connection',
 'Raymond Weil',
 'Parosh',
 'Rochas',
 'ECCO',
 'Rixo',
 'Hunter',
 'Franck Muller',
 'Retrosuperfuture',
 'Haider Ackermann',
 'Edwin',
 'Fred',
 'The Frankie Shop',
 'Nicholas Kirkwood',
 'Miista',
 'Maliparmi',
 'Nautica',
 'BORBONESE',
 'ALDO',
 'NAF NAF',
 'Hublot',
 'David Yurman',
 'MOTIVI',
 'De Fursac',
 'Alexandre Vauthier',
 'Kangol',
 'Skims',
 'Stine Goya',
 "L'Agence",
 'Maison Margiela X Reebok',
 'Marciano',
 'Orlebar Brown',
 'Equipment',
 'Calvin Klein 205W39NYC',
 'Alberto Guardiani',
 'Ralph Lauren Denim & Supply',
 'Russell & Bromley',
 'Daks',
 'PENNYBLACK',
 'Charvet',
 'Nike x Sacaï',
 'LUMBERJACK',
 'ROBERTA DI CAMERINO',
 'SKECHERS',
 'Soeur',
 'Christopher Kane',
 'Eric Bompard',
 'Maserati',
 'PACIOTTI',
 'Impérial',
 'Nike x Supreme',
 'Seventy',
 'Moon Boot',
 'GAUDI',
 'Fiorucci',
 'Yves Salomon',
 'BUFFALO',
 'Genny',
 'Love Shack Fancy',
 'Stella McCartney Pour Adidas',
 'Tibi',
 'Vince  Camuto',
 'RHUDE',
 'Number Nine - Takahiro Miyashita',
 'MORGAN',
 'Peserico',
 'Coccinelle',
 'G-STAR RAW',
 'Alden',
 'T by Alexander Wang',
 'Fjallräven',
 'Frankie Morello',
 'Colombo',
 'EL CORTE INGLES',
 'Donna Karan',
 'MARIO VALENTINO',
 'Boglioli',
 'Patek Philippe',
 'Disney x Gucci',
 'Dorothee Schumacher',
 'MANILA GRACE',
 'Kansai Yamamoto',
 'Daniel Wellington',
 'Aeyde',
 'Charles Jourdan',
 'Carel',
 'Jaeger',
 'Hobbs',
 'Michele',
 'Plein Sud',
 'Charles Philip Shanghai',
 'Filling Pieces',
 'Officine Creative',
 'Kapital',
 'Flavio Castellani',
 'DENNY ROSE',
 'Norma Kamali',
 'JOHNNY WAS',
 'Eterna',
 'Baume & Mercier',
 'Tosca Blu',
 'Billionaire Boys Club',
 'Dainese',
 'Aje',
 'Audemars Piguet',
 'J.Lindeberg',
 'BAGUTTA',
 'SARTORIA ITALIANA',
 'mcleonard',
 'Jonathan Simkhai',
 'Maurice Lacroix',
 'KOOKAI',
 'Re/Done',
 'Margaret Howell',
 'Gai Mattiolo',
 'HIGH',
 'Franco Ferrari',
 'Faith Connexion',
 'Giambattista Valli',
 'Alessandra Rich',
 'Renato Balestra',
 'Claude Montana',
 'Antik Batik',
 'Aigle',
 'Maison Mihara Yasuhiro',
 'EDEN PARK',
 "Roy Roger's",
 'Roland Mouret',
 'NBA',
 'Carshoe',
 'Orient',
 'Vivienne Westwood Red Label',
 'Opening Ceremony',
 'Badgley Mischka',
 'BRACCIALINI',
 'Karl Kani',
 'CONTE OF FLORENCE.',
 'Baum Und Pferdgarten',
 'Ted Lapidus',
 'Georges Rech',
 'Han Kjobenhavn',
 'Joseph Ribkoff',
 'Ralph Lauren Double Rl',
 'Adidas X Ivy Park',
 'Elie Tahari',
 'Johnstons Of Elgin',
 'L AUTRE CHOSE',
 'Aime Leon Dore',
 'Furbysd',
 'Nfl Team Apparel',
 'Hoss Intropia',
 'Incotex',
 'Pretty Ballerinas',
 'Kith',
 'PURIFICACION GARCIA',
 'Nine West',
 'Alexandre Birman',
 'Mou',
 'Chie Mihara',
 'Pringle Of Scotland',
 'River Island',
 'Manuel Ritz',
 'Joie',
 'Erdem',
 "Alessandro Dell'Acqua",
 'Adidas x Raf Simons',
 'HARRIS TWEED',
 'Manoush',
 'Balenciaga X Adidas',
 'BARRETT',
 'Dion Lee',
 'Pt01',
 'Diesel Black Gold',
 'DOCKERS',
 'Alanui',
 'Sonia by Sonia Rykiel',
 'SAVE THE QUEEN',
 'Pyrenex',
 'Needle & Thread',
 'Walter Van Beirendonck',
 'Polaroid',
 'Citizens Of Humanity',
 'Des Petits Hauts',
 'Gianmarco Lorenzi',
 'Jott',
 'Alfred Dunhill',
 'Peak Performance',
 'Gia Borghini',
 'NUDIE JEANS',
 'FORNARINA',
 'DANIEL HECHTER',
 'Fusalp',
 'Réalisation',
 'SANDRO FERRONE',
 'Mes Demoiselles ...',
 'LOTTO',
 'Martine Rose',
 'Cinq à Sept',
 'Supreme x The North Face',
 'Ancient Greek Sandals',
 'Wood Wood',
 'QUICKSILVER',
 'Agnona',
 'Everlane',
 'Paige',
 'For Love & Lemons',
 'Takahiromiyashita The Soloist',
 'Liviana Conti',
 'Silvian Heach',
 'Talbots',
 'FESTINA',
 'LE COQ SPORTIF',
 'Dive divine',
 'Barba',
 'Vic Matié',
 'Piaget',
 'Baldessarini',
 'ANIYE BY',
 'Mizuno',
 'MC2 Saint Barth',
 'Prima donna',
 'Alexis',
 'Sutor Mantellassi',
 'Edward Green',
 'Viktor & Rolf',
 'Dune',
 'I BLUES',
 'Gentle Monster',
 'Loeffler Randall',
 'Chaps',
 'Pedro Del Hierro',
 'Mitchell & Ness',
 'Basile',
 'Craig Green',
 'Les Hommes',
 'G-Shock',
 'Autry',
 'Coperni',
 'Ksubi',
 'BATA',
 'Tombolini',
 'Simone Rocha',
 'VON DUTCH',
 'Nili Lotan',
 'HAVAIANAS',
 'Norse Projects',
 'DIXIE',
 'Sportalm',
 'Brooks',
 'PURA LOPEZ',
 'Sessun',
 'Custo Barcelona',
 'Sunnei',
 'Marina Yachting',
 'Suicoke',
 'Valentino by mario valentino',
 'Strellson',
 'Anne Fontaine',
 'Sector',
 'Lacoste Live',
 'Agl',
 'Retrofête',
 'Eric Emanuel',
 'EXPRESS',
 'JACQUES MARIE MAGE',
 'Stand studio',
 'P448',
 'Sundek',
 'Rebecca Taylor',
 'Corum',
 'Floris Van Bommel',
 'Blundstone',
 'Saga Furs',
 'Jigsaw',
 'Playboy',
 'Rupert Sanderson',
 'ROBERTO BOTTICELLI',
 'Saks Fifth Avenue Collection',
 'Bel Air',
 'Camilla',
 'PIERO GUIDI',
 'Jucca',
 'Mykita',
 'Obey',
 'Current Elliott',
 'Cesare Attolini',
 'BEN SHERMAN',
 'PAOLO PECORA',
 'Elie Saab',
 'Travis Scott',
 'Onitsuka Tiger',
 'Faithfull The Brand',
 'Boden',
 'Fur deluxe',
 'GATTINONI',
 'Maison Scotch',
 'Diadora Heritage',
 'Akris',
 'Allegri',
 'Nodaleto',
 'Liberty Of London',
 'Stetson',
 'Windsor',
 'Guidi',
 'Drykorn',
 'Alo',
 'Elena Miro',
 'Rodebjer',
 'Unisa',
 'TAMARIS',
 'Barneys New York',
 'Oakwood',
 'On Running',
 'Rat & Boa',
 'LOTTUSSE',
 'Oamc',
 'Oris',
 'Bobbies',
 'Laurel',
 'Nike x Stussy',
 'Boucheron',
 'Vineyard Vines',
 'Azzaro',
 'Luciano Padovan',
 'Raey',
 'Cutler & Gross',
 "L'AUTRE CHOSE",
 'Fendissime',
 'Toga Pulla',
 'Rains',
 'Hogl',
 'BILLABONG',
 'Nike x Comme Des Garçons',
 'Nordstrom',
 'Maharishi',
 'TOGA',
 'Alohas',
 'Melvin&Hamilton',
 'Beams',
 'Francesco Smalto',
 'Suncoo',
 'Girard Perregaux',
 'Frederique Constant',
 'SAN MARINA',
 'CARATSDIRECT2U',
 'Berwich',
 'Harris',
 'Loulou studio',
 'AERONAUTICA MILITARE',
 'CARACTERE',
 'ANNE KLEIN',
 'Milly',
 'Matthew Williamson',
 'Vera Wang',
 'Sartore',
 'Holzweiler',
 'Scanlan & Theodore',
 'Kennel Und Schmenger',
 'Marimekko',
 'GUTTERIDGE',
 'FRACOMINA',
 'Lozza',
 'Gina',
 'Spyder',
 'LORIBLU',
 'STEPHANE KELIAN',
 'GALERIES LAFAYETTE',
 'Cruciani',
 'Luisa Cerano',
 'TOUS',
 'Hope',
 'KANGRA',
 'Baume Et Mercier',
 'SHANGHAI TANG',
 'Moma',
 'Aries',
 'MCS',
 'GOOD AMERICAN',
 'Ruslan Baginskiy',
 'Victoria, Victoria Beckham',
 'Gestuz',
 'NAVYBOOT',
 'Roberto Collina',
 'UNITED NUDE',
 'Athleta',
 'Bell & Ross',
 'DC SHOES',
 'James Perse',
 'A.L.C',
 'CELIO',
 'Maui Jim',
 'Studio Nicholson',
 'Goorin Bros',
 'Moncler x Palm Angels',
 'Melissa',
 'Henry Cotton',
 'Anna Sui',
 'Gia Couture',
 'Max & Moi',
 'Gmbh',
 'Sun 68',
 'Paloma Wool',
 'Mellow Yellow',
 'BEBE',
 'GALLO',
 'Bolle',
 'Pedro Garcia',
 'Lovers + Friends',
 'MAMMUT',
 'Antonio Marras',
 'RRD',
 'ROBERT GRAHAM',
 'Maison 123',
 'Misa',
 'Lola Cruz',
 'ANTICA SARTORIA',
 'Giorgio Passigatti',
 'Berenice',
 ...]

Scraping Google Trends is notoriously tedious, we can expect to eventually get IP banned. We resume scraping from the last brand that was scraped and we randomly rotate between agents.

In [17]:
res = "google_trends_all_brands.csv"

try:
    existing = pd.read_csv(res)
    done_brands = set(existing["brand"].unique())
except FileNotFoundError:
    existing = pd.DataFrame()
    done_brands = set()

agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    "Mozilla/5.0 (X11; Linux x86_64)",
]

Note that for brands with high counts, batch processing did not work.

We scraped worldwide, in the last 12 months and added random wait times if we encounter an error.

In [12]:
def fetch_trends_batch(brands, max_retries=5):
    """
    Fetch Google Trends data for a list of brands in a single batch.
    Returns a tidy DataFrame with columns: date, value, isPartial, brand.
    """
    for attempt in range(1, max_retries + 1):
        try:
            ua = random.choice(agents)
            pytrends = TrendReq(hl="en-US", tz=360, retries=0, backoff_factor=0)
            pytrends.headers["User-Agent"] = ua

            pytrends.build_payload(brands, timeframe="today 12-m", geo="")
            df = pytrends.interest_over_time()

            if df.empty:
                return None

            df = df.reset_index()

            value_cols = [b for b in brands if b in df.columns]
            df_tidy = df.melt(
                id_vars=["date", "isPartial"], 
                value_vars=value_cols, 
                var_name="brand", 
                value_name="value"
            )

            return df_tidy[["date", "value", "isPartial", "brand"]]

        except Exception as e:
            if "429" in str(e):
                wait = random.uniform(3, 9)
                print(f"429 detected, waiting {wait:.1f}s before retrying...")
                time.sleep(wait)
            else:
                print(f"Error: {e}")
                time.sleep(2)
    return None

We add another random delay between batches.

In [ ]:
all_results = []
counter = 0
batch_size = 5  

for i in range(0, len(brands_sorted), batch_size):
    batch = [b for b in brands_sorted[i:i + batch_size] if b not in done_brands]
    if not batch:
        continue

    print(f"Fetching batch: {batch}")
    df = fetch_trends_batch(batch)

    if df is not None:
        all_results.append(df)

        
        pd.concat([existing] + all_results, ignore_index=True).to_csv(res, index=False)
        existing = pd.read_csv(res)  
        all_results = [] 
    else:
        print(f"{batch}: no data or failed after retries")

    time.sleep(random.uniform(3, 7))

    counter += len(batch)
    if counter % 50 == 0:
        print(f"{counter} brands processed")

Fetching batch: ['360 Cashmere', 'Laundry by Shelli Segal', 'EDOX', 'HTC Los Angeles', 'Repeat']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Part Two', 'VIA DELLE PERLE', 'NICE THINGS', 'Iris & Ink', 'JET SET']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Alberto Biani', 'Eddy Monetti', 'Petit Bateau', 'Cinti', 'Princesse Tam Tam']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['SEE U SOON', 'Octobre Editions', 'Lasserre', 'Baobab', 'Superdown']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ["Reptile's House", 'Musto', 'Laneus', 'L.A.M.B', 'Del Toro']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Sunday Somewhere', 'CIVIDINI', 'SER.O.YA', 'ZU ELEMENTS', 'TW Steel']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Zuiki', 'Stutterheim', 'Paul Stuart', 'Marchesa', 'BLANKNYC']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Del Mare 1911', 'Lana', 'Billi Bi', 'IMPRESSED JEWELRY', 'Armand Ventilo']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Entire Studios', 'Berghaus', 'Sunspel', 'Dissh', 'Namacheko']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Islo', 'Aspinal Of London', 'Likely', 'Mastermind Japan', 'Olivia Rubin']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

50 brands processed
Fetching batch: ['Vivienne Tam', 'JUUN.J', 'Natan', 'Prps', 'ECOALF']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Louis Vuitton x Nigo', 'Arte', 'Chimi', 'Peruvian Connection', 'IRREGULAR CHOICE']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Harry Winston', 'Attic And Barn', 'Mansur Gavriel', 'Betsy & Adam', 'Ariat']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['London fog', 'LAZZARI', 'Francesco Russo', 'Cordova', 'Meshki']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Aidan Mattox', 'Ivy Park', 'Judith Leiber', 'Solid & Striped', 'Mrz']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Babylon', 'YUME YUME', 'Divine Follie', 'Haute Hippie', 'Skall Studio']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['FRANCO SARTO', 'Mark Mc Nairy', 'Colette', 'Hai', 'Djerf Avenue']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['AGR', 'Devotion Twins', 'Sprung Frères', 'DIEGA', 'Brandy Melville']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['Barrie', 'Aethera', 'Adidas x Craig Green', 'Lack Of Colour', 'Jack Wills']

/opt/anaconda3/envs/ecl-course-2025/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

Fetching batch: ['No faith studio', 'Finamore', 'Oxford', 'Sunflower', 'LES PETITES BOMBES']
429 detected, waiting 5.7s before retrying...
429 detected, waiting 7.3s before retrying...

KeyboardInterrupt:

In [18]:
len(done_brands)

2195

The code was run repeatedly, IP bans occurred every 5 minutes after which, the IP address must be changed via using a VPN to rerun the code.

In [19]:
df = pd.read_csv('google_trends_all_brands.csv')

df

                       date  isPartial             brand  value
0       2024-11-24 00:00:00      False  Max Mara Weekend     91
1       2024-12-01 00:00:00      False  Max Mara Weekend     73
2       2024-12-08 00:00:00      False  Max Mara Weekend     75
3       2024-12-15 00:00:00      False  Max Mara Weekend     72
4       2024-12-22 00:00:00      False  Max Mara Weekend     90
...                     ...        ...               ...    ...
116542  2025-10-26 00:00:00      False        Jack Wills      4
116543  2025-11-02 00:00:00      False        Jack Wills      4
116544  2025-11-09 00:00:00      False        Jack Wills      4
116545  2025-11-16 00:00:00      False        Jack Wills      5
116546  2025-11-23 00:00:00       True        Jack Wills      5

[116547 rows x 4 columns]

In [20]:
df['value'] = df['value'].apply(float)

Compute for each brand, the mean popularity value.

In [30]:
res = df.groupby(['brand'],as_index=False)['value'].mean()

res

                       brand      value
0            & Other Stories  62.811321
1                 (+) PEOPLE  83.283019
2                       032c   0.000000
3     10 Crosby by Derek Lam   0.000000
4              1017 ALYX 9SM   0.000000
...                      ...        ...
2190                 octopus  28.000000
2191           takeo kikuchi   4.018868
2192                 valstar   0.000000
2193                 yamamay   0.000000
2194           Études Studio   0.000000

[2195 rows x 2 columns]

In [31]:
res.to_csv('brand_popularity_mean.csv')